CC = gcc
CFLAGS = -g -Wall -O0
#INC = 
SRC = pth_ll_one_mut.c
SRC2 = pth_ll_mult_mut.c
DEF = -lpthread

all:
	$(CC) $(CFLAGS) -o ./run $(SRC) $(DEF)
1:
	$(CC) $(CFLAGS) -o ./run $(SRC) $(DEF)
2:
	$(CC) $(CFLAGS) -o ./run $(SRC2) $(DEF)
clean:
	rm -rf ./run