CC=gcc
CFLAGS=-g -Wall 
SRC=./YUXUAN_JING_Ex0_1_a.c 
LIB = -lm

all:
	$(CC) $(CFLAGS) -o ./run $(SRC)
	echo "compile_done"
1:
	$(CC) $(CFLAGS) -o ./run1 YUXUAN_JING_Ex0_1_a.c $(LIB)
	echo "compile_YUXUAN_JING_Ex0_1_a.c"
2:
	$(CC) $(CFLAGS) -o ./run2 YUXUAN_JING_Ex0_2_a.c $(LIB)
	echo "compile_YUXUAN_JING_Ex0_2_a.c"
3:
	$(CC) $(CFLAGS) -o ./run3 YUXUAN_JING_Ex0_3_a.c $(LIB)
	echo "compile_YUXUAN_JING_Ex0_3_a.c"
4:
	$(CC) $(CFLAGS) -o ./run4 YUXUAN_JING_Ex0_4_a.c $(LIB)
	echo "compile_YUXUAN_JING_Ex0_4_a.c"
5:
	$(CC) $(CFLAGS) -o ./run5 YUXUAN_JING_Ex0_5_a.c $(LIB)
	echo "compile_YUXUAN_JING_Ex0_5_a.c"
5a:
	$(CC) $(CFLAGS) -o ./run5a YUXUAN_JING_Ex0_5_a.c $(LIB)
	echo "compile_YUXUAN_JING_Ex0_5_a.c"
5b:
	$(CC) $(CFLAGS) -o ./run5b YUXUAN_JING_Ex0_5_b.c $(LIB)
	echo "compile_YUXUAN_JING_Ex0_5_b.c"

clean:
	rm -rf ./run*
